version: "3.8"

services:
    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=produtos_db
            - DB_USERNAME=root
            - DB_PASSWORD=senha_do_mysql

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: senha_do_mysql
            MYSQL_DATABASE: produtos_db
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
